version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - batchspawner
  - docstrings
  - markdownlint
  - sbatch
  - scancel
  - sdist
  - Slurm
  - slurmspawner
  - squeue
  - venv
ignoreWords: []
import: []
